### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by conorcogan** [0xfff0800/info-instagram#2]
Whenever I type in python3 setup.py install it comes up with this:

running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/test-easy-install-5157.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

And whenever I type python3 FaLaH.py it comes up with this:

Traceback (most recent call last):
  File "FaLaH.py", line 1, in <module>
    from toutatis import *
  File "/home/conorcogan/info-instagram/info-flo/toutatis/__init__.py", line 1, in <module>
    from toutatis.core import *
  File "/home/conorcogan/info-instagram/info-flo/toutatis/core.py", line 3, in <module>
    from quidam import instagram
ModuleNotFoundError: No module named 'quidam'

Does anyone know how to fix this? Please I am very stuck

**Comment by conorcogan** [comment]
Solved it, instead of typing python3 setup.py install, type python3 setup.py install --user, then everything should work properly.
